FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV FLASK_APP=main.py
ENV PYTHONUNBUFFERED=1

ENTRYPOINT [ "python" ]

CMD ["main.py"]
