FORMAT: 1A
HOST: https://soa.strycks.dpdns.org

# Book Management API

Simple API to manage library books.

# Group Books

## Books Collection [/api/v1/books]

### List All Books [GET]
+ Response 200 (application/json)
    + Attributes (array[Book])

### Create Book [POST]
+ Request (application/json)
    + Attributes (BookBase)

+ Response 201 (application/json)
    + Attributes (Book)

## Book Details [/api/v1/books/{id}]

+ Parameters
    + id: 1 (number, required) - Book ID

### Get Book [GET]
+ Response 200 (application/json)
    + Attributes (Book)

### Replace Book [PUT]
+ Request (application/json)
    + Attributes (BookBase)

+ Response 200 (application/json)
    + Attributes (Book)

### Partial Update [PATCH]
+ Request (application/json)
    + Attributes
        + year: 2027 (number, optional)

+ Response 200 (application/json)
    + Attributes (Book)

### Delete Book [DELETE]
+ Response 204

# Data Structures

## BookBase (object)
+ title: `Dota Dragon's Blood` (string, required)
+ author: `valve, icefrog` (string)
+ year: 2026 (number)

## Book (BookBase)
+ id: 1 (number)