#%RAML 1.0
title: Book Management API
version: v1
baseUri: https://soa.strycks.dpdns.org/api/v1
mediaType: application/json

types:
  Book:
    type: object
    properties:
      id: integer
      title: 
        type: string
        required: true
      author: string
      year: integer

/books:
  get:
    description: Get all books
    responses:
      200:
        body:
          application/json:
            type: Book[]

  post:
    description: Create a new book
    body:
      application/json:
        type: Book
    responses:
      201:
        body:
          application/json:
            type: Book

  /{id}:
    get:
      description: Get book details
      responses:
        200:
          body:
            application/json:
              type: Book
    
    put:
      description: Replace a book
      body:
        application/json:
          type: Book
      responses:
        200:
          body:
            application/json:
              type: Book

    patch:
      description: Update book fields
      body:
        application/json:
          type: object
          properties:
            title?: string
            author?: string
            year?: integer
      responses:
        200:
          body:
            application/json:
              type: Book

    delete:
      description: Remove a book
      responses:
        204: