global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'soa-app'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['soa.strycks.dpdns.org']
